Add the capability to verify more integrity factors
mavenlink/changestream pull request #110
Opened 2022-03-11 01:12 UTC by jacksenechal

In order to verify more than just the table name matching, we also need
row data. We'll be able to do things like match the fields and values in
the SQL to the tuples in the row data.

2022-03-14 16:07 UTC, cpalafox requested changes
Saw some places we need to change stuff at to fix build problems

2022-03-14 16:07 UTC, cpalafox commented on src/main/scala/changestream/ChangeStreamEventListener.scala
> +        val rowData = getRowData(e)
this bit is failing due to type mismatch, given e is a `MutationEvent`, while RowData needs a `MutationWithInfo`

what we can do here is.

```
val mutationWithInfo = MutationWithInfo(e, nextPosition)
val rowData = getRowData(mutationWithInfo)

IntegrityVerifier.verify(e.tableName, e.sql.getOrElse(""), nextPosition, rowData, "ChangestreamEventListener")
transactionActor ! mutationWithInfo
```

2022-03-14 16:07 UTC, cpalafox commented on src/main/scala/changestream/IntegrityVerifier.scala
> +  def verify(tableName: String, sql: String, position: String, rowData: Seq[ListMap[String, JsValue]], source: String = ""): Boolean = {
we provide rowData here but we don't use it? is it just it being WIP?

2022-03-14 16:07 UTC, cpalafox commented on src/main/scala/changestream/RowDataExtractor.scala
> +  val truncationText: String = "...[TRUNCATED]"
I think the JsonFormatterActorSpec was using this data, so we'll need to change that

2022-09-08 00:47 UTC, jacksenechal commented
Archiving

2022-09-08 00:47 UTC, closed without merging